

name: Update TV Logos

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs once a week (Sunday at midnight UTC)
  workflow_dispatch:    # Allow manual triggering

jobs:
  update-logos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run logo update script
        run: python copy_tv_logos.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update TV logos" || echo "No changes to commit"
          git push